#!/bin/bash


read -e -p "Define directory to save mdot :~/" -i "mdot" path_install

echo ""

path_install=~/$path_install
echo $path_install
echo "**** Download repository mdot"
git clone https://github.com/jhonromerou/mdot $path_install
echo ""

cd $path_install
chmod +x install

echo ""
echo ""
echo -e "**** Installing mdot "
./install