#!/bin/bash

# TODO: translate to english

MDOT_BIN="$PWD"
MDOT_INI="$MDOT_BIN/mdot-ini"
source $MDOT_BIN/.mdot/core

# Inicio de configuración
i_title "Configuradno MDOT para su usuario"

# Limpiar configuracion anterior de mdot
file_source=~/.bashrc
id_mdot="# mdot library"

num=$(grep -n "$id_mdot" $file_source \
    | awk -F ":" '{ print $1 }' \
    | head -1
)
if [[ $num ]]; then
    lines_del="$num,$(( $num +2 ))d"
    sed -i $lines_del $file_source

    i_title "mdot unistall!"
fi

i_read "Desea ejecutar mdot globalmente? :" \
    -i "Y" useGlobal

# Defines id and path_global
echo "$id_mdot" >> "$file_source"
echo "MDOT_BIN=\"$MDOT_BIN\"" >> "$file_source"

if [[ "$useGlobal" == "Y" ]]; then
    cmd_defined="source $MDOT_INI"
else
    cmd_defined="alias mdot='source $MDOT_INI'"
fi
echo "$cmd_defined" >> "$file_source"

i_title "Usando mdot:"

if [[ "$isGlobal" == "Y" ]]; then
    i_echo "Ejecutar cualquier usando ${C_RED}m-xxx${C_NC}. Ej: ${C_RED}m-help${C_NC}"
else
    i_echo "1. Ejecutar ${C_RED}mdot${C_NC} en la consola para habilitar temporalmente."
    i_echo "2. Ejecutar cualquier usando {${C_RED}m-xxx${C_NC}. Ej: ${C_RED}m-help${C_NC}"
fi
