#!/bin/bash

# $MDOT_BIN  Must define in .bashrc when install
MDOT_INI="$MDOT_BIN/mdot-ini"
source $MDOT_BIN/.env
source $MDOT_BIN/.mdot/core
source $MDOT_BIN/.mdot/loader

# ------ CONSTRAINTS -----------------
 # MDOT_E_x = Must Defines in $MDOT_BIN/.env
# ------

# Saves directory to return it when command uses cd <path>
MDOT_PWD=$PWD
MDOT_TMP="mdot-temp"

# Path of libraries
MDOT_MODULES=$MDOT_BIN/lib;

# Paths of help configuration
MDOT_HELP="$MDOT_BIN/help";
MDOT_HELP_CMDS="$MDOT_HELP/.commands"
MDOT_HELP_LIST="$MDOT_HELP/.commands/.list";


# Start
# Imports and defines wikis
mdot-loader-imports
mdot-loader-custom-imports
if ! [ -f $MDOT_HELP_LIST ]; then
    mdot-loader-wikis
fi
# Clear mdot internal libraries
mdot-core-clear
mdot-loader-clear

# Deletes mdot temporary
function mdot-clear()
{
    if [ $(declare -Ff m-phpunit-clear) ]; then
        m-phpunit-clear
    fi
    rm -rf $MDOT_TMP
}

# Lists all commands and shows help
function mdot-help()
{
    cd $MDOT_HELP_CMDS
    if [ -f "$1" ]; then
        cat $1
    else
        METHOD_NAME=$(ls -1 \
            | fzf --color="light" --preview="head {}"
        )
        if [ -f "$METHOD_NAME" ]; then
            cat $METHOD_NAME
        fi
    fi

    i_mdot_pwd
}