#!/bin/bash

# $MDOT_BIN  Must define in .bashrc when install
MDOT_INI="$MDOT_BIN/mdot-ini"
source $MDOT_BIN/.env
source $MDOT_BIN/.mdot/core
source $MDOT_BIN/.mdot/loader

# ------ CONSTRAINTS -----------------
 # MDOT_E_x = Must Defines in $MDOT_BIN/.env
# ------

# Saves directory to return it when command uses cd <path>
MDOT_PWD=$PWD

# Path of libraries
MDOT_MODULES=$MDOT_BIN/lib;

# Paths of help configuration
MDOT_HELP="$MDOT_BIN/help";
MDOT_HELP_CMDS="$MDOT_HELP/.commands"
MDOT_HELP_LIST="$MDOT_HELP/.commands/.list";


# Start
if [ "$MDOT_LOADED" = true ]; then
    i_title "MDOT is loaded"
    i_echo "If whant reload all use: mdot-reload"
    
else
    # Just one loaded!
    MDOT_LOADED=true

    # Imports and defines wikis
    mdot-loader-imports
    mdot-loader-custom-imports
    mdot-loader-wikis

    # Clear mdot internal libraries
    mdot-core-clear
    mdot-loader-clear
fi

# Lists all commands and shows help
function m-help()
{
    cd $MDOT_HELP_CMDS
    METHOD_NAME=$(ls -1 \
        | fzf --color="light" --preview="head -100 {}"
    )
    if test -f "$METHOD_NAME"; then
        less $METHOD_NAME
    fi
    cd $MDOT_PWD
}