#!/usr/bin/env bash

function m-artisan-bcrypt()
{
    DEP_ERR=$(php artisan --execute="" 2>&1 | grep 'composer')
    if [[ $DEP_ERR ]]; then
        echo -e "**** Composer is required"
        php artisan --execute=""
    else
        if [[ $1 ]]; then
            TO_ENCRYPT=$1
        else
            read -e -p "Define contain to encrypt: " TO_ENCRYPT
        fi
    
        ENCRYPT=$(php artisan tinker --execute="echo bcrypt('$TO_ENCRYPT')")

        echo $ENCRYPT
        m-copy $ENCRYPT
    fi
}

# TODO:
# Obtener contenido desencriptado utilizando decrypt de laravel
 # m-artisan-bcrypt "password-1234": Encriptar directamente
function m-artisan-decrypt()
{
    if [[ $1 ]]; then
        TO_DECRYPT=$1
    else
        read -e -p "Digite el contenido a encriptar: " TO_DECRYPT
    fi

    DECRYPT=$(php artisan tinker --execute="echo decrypt('$TO_DECRYPT')")
    echo $DECRYPT
    m-copy $DECRYPT
    echo "**** Copiado en el portapapeles"
}

function m-artisan-logs()
{
    PATH_LOGS="storage/logs"
    SELECTED=$(ls -1 $PATH_LOGS \
    | grep -E '\.log$' \
    | fzf -1)

    if [[ $SELECTED ]]; then
        FILE_SELECTED="$PATH_LOGS/$SELECTED"
        if [[ $1 == "-f" ]]; then
            echo "**** Follow change of $FILE_SELECTED"
            tail -n0 -f $FILE_SELECTED
        else
            less $FILE_SELECTED
        fi
    fi
}

function m-artisan-clear()
{
    # Remove the route,view cache file
    php artisan cache:clear \
    php artisan view:clear \
    php artisan route:clear \
    # Remove the cached bootstrap files
    php artisan optimize:clear
    # Recreate boostrap/cache/compiled.php
    php artisan optimize
}

function m-artisan-serve() {
    php artisan optimize
    php artisan serve $@
}

function m-artisan-test()
{
    if [ -f "artisan" ]; then
        i_mdot_title "*** --env=testing"
        php artisan optimize --env=testing
    fi
}