#!/usr/bin/env bash

# Copia temporal de composer.json para no afectar los proyectos
function m-composer-json-backup()
{
    cp composer.json composer-mbk.json
    cp composer.lock composer-mbk.lock
}

# Restaurar copia temporal de composer.json para no afectar los proyectos
function m-composer-json-restore()
{
    mv composer-mbk.json composer.json 2> /dev/null
    mv composer-mbk.lock composer.lock 2> /dev/null
}

function m-composer-required()
{
     if ! ([ -f "composer.json" ] && [ -d "vendor" ]); then
        i_mdot_err "Composer is required but not found."
    fi
}

function m-composer-package-v()
{
    isRequired=$(m-composer-required)
    if [ "$isRequired" ]; then
        return
    fi

    package_name=$1
    version=$(composer show | grep "$package_name" \
        | head -1 \
        | awk '{ print $2 }'
    )
    echo $version
}