#!/usr/bin/env bash

function m-text-blines()
{
    line_ini=$1
    line_end=$(( $2-line_ini+1 ))
    file=$3
    tail +$line_ini $file | head -$line_end
}

function m-copy()
{
    if [ "$1" = "-s" ]; then
        shift
    else
        echo "**** Copy on clipboard"
    fi

    echo "$@" | tr -d '\n\r' | xclip -selection clipboard
}